name: reconstruct_climate_indices
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - pip
  - setuptools
  - numpy
  - scipy
  - pandas
  - xarray
  # Jupyter
  - jupyter
  - jupyterlab
  - yaml 
  - mlflow
  - scikit-learn
  - tqdm
  - pip :
    # The kalman_reconstruction package is not yet available on PyPI, so we install it directly from GitHub
    - "git+https://github.com/nilsnevertree/kalman-reconstruction-partially-observed-systems"
