name: test_env_env_reconstruct_climate_indicies
channels:
  - conda-forge
dependencies:
  - python=3.9
  ############## These will have to be adjusted to your specific project
  - numpy
  - scipy
  - pandas
  - sklearn
  ##############
  - pytest
  - pip:
      - codecov
      - pytest-cov
      - coverage[toml]
