name: reconstruct_climate_indices_docs
dependencies:
   - python=3.9
   # If your docs code examples depend on other packages add them here
   - numpy
   - scipy
   - pandas
   - xarray
   - scikit-learn
   - tqdm
   - yaml
   # These are needed for the docs themselves
   - numpydoc
   - sphinx
  #  - sphinx_rtd_theme
  #  - ipython
  #  - nbconvert
  #  - nbformat
  #  - ipykernel
  #  - pandoc
   - pip
   - pip:
    #  - docrep
     - nbsphinx
    #- jupyter_client
    # sphinx packages
     - sphinx_automodapi
     - sphinx_mdinclude
    #- sphinx_pangeo_theme
     - sphinx-copybutton
     - pydata-sphinx-theme
     - sphinxcontrib-srclinks
    # The kalman_reconstruction package is not yet available on PyPI, so we install it directly from GitHub
     - "git+https://github.com/nilsnevertree/kalman-reconstruction-partially-observed-systems"
