name: reconstruct_climate_indices_docs
dependencies:
   - python=3.9
   # If your docs code examples depend on other packages add them here
   - numpy
   - xarray
   # These are needed for the docs themselves
   - numpydoc
   - sphinx
   - sphinx_rtd_theme
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - pip
   - yaml
   - pip:
     - docrep<=0.2.7
     - nbsphinx
     - jupyter_client
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - pydata-sphinx-theme
     - sphinxcontrib-srclinks
